insert or replace into LocalizedText
    (Language,      Tag,                                                    Text)
values
    ("zh_Hans_CN",  "LOC_POLICY_GOD_KING_DESCRIPTION",                      "[ICON_CAPITAL] 首都+2 [ICON_FAITH] 信仰值。"),
    ("zh_Hans_CN",  "LOC_POLICY_DISCIPLINE_DESCRIPTION",                    "同蛮族战斗时，+10 [ICON_STRENGTH] 单位战斗力。"),
    ("zh_Hans_CN",  "LOC_POLICY_SURVEY_DESCRIPTION",                        "侦察单位获得的经验值翻倍，且驻扎时额外回复5点生命值。"),
    ("zh_Hans_CN",  "LOC_POLICY_CARAVANSARIES_DESCRIPTION",                 "所有贸易路线+2 [ICON_GOLD] 金币。每回合+2  [ICON_GREATMERCHANT]  大商人点数。"),
    ("zh_Hans_CN",  "LOC_POLICY_MARITIME_INDUSTRIES_DESCRIPTION",           "生产远古和古典时代的海军单位加速+50%，城市拥有港口时或每有一级港口建筑时多50%。"),
    ("zh_Hans_CN",  "LOC_POLICY_ILKUM_DESCRIPTION",                         "+30% 建造者 的生产速度。"),
    ("zh_Hans_CN",  "LOC_POLICY_CAPITAL_DESCRIPTION",                       "首都建造区域时+25%  [ICON_PRODUCTION] 生产力，若此时首都没有专业区域则额外+25%  [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_POLICY_AGOGE_DESCRIPTION",                         "生产远古和古典时代的陆军单位加速+25%，城市拥有军营时或每有一级军营建筑时多25%。"),
    ("zh_Hans_CN",  "LOC_POLICY_CORVEE_DESCRIPTION",                        "为远古和古典奇观+30%建造速度。所有城市-2 [ICON_Amenities] 宜居度。"),
    ("zh_Hans_CN",  "LOC_POLICY_COLONIZATION_DESCRIPTION",                  "生产开拓者时+25%建造速度，若城市至少拥有6人口则再+25%建造速度。"),
    ("zh_Hans_CN",  "LOC_POLICY_STRATEGOS_DESCRIPTION",                     "每回合+2 [ICON_GREATGENERAL] 大将军点数。任一项相邻加成不少于2的军营，其专家产出的 [ICON_GREATGENERAL] 大将军点数额外+2。"),
    ("zh_Hans_CN",  "LOC_POLICY_INSPIRATION_DESCRIPTION",                   "每回合+2 [ICON_GREATSCIENTIST] 大科学家点数。相邻加成不少于3的学院，其专家产出的 [ICON_GREATSCIENTIST] 大科学家点数额外+2。"),
    ("zh_Hans_CN",  "LOC_POLICY_REVELATION_DESCRIPTION",                    "每回合+2 [ICON_GREATPROPHET] 大预言家点数。相邻加成不少于3的圣地，其专家产出的 [ICON_GREATPROPHET] 大预言家点数额外+2。"),
    ("zh_Hans_CN",  "LOC_POLICY_COOPERATIVE_COMBAT_DESCRIPTION",            "陆地单位夹击与支援战斗力加成+50%。"),
    ("zh_Hans_CN",  "LOC_POLICY_CHARISMATIC_LEADER_DESCRIPTION",            "开放所有城邦的边境，影响力点数每回合+3。"),
    ("zh_Hans_CN",  "LOC_POLICY_TRIBUTE_DESCRIPTION",                       "作为宗主国，从每个下属城邦获得+1 [ICON_SCIENCE] 科技值和+1 [ICON_CULTURE] 文化值。"),
    ("zh_Hans_CN",  "LOC_POLICY_HEDONISM_DESCRIPTION",                      "建造娱乐中心以及其中的建筑时+25%建造速度，若该城市宜居度不小于4，则额外+25%建造速度。"),
    ("zh_Hans_CN",  "LOC_POLICY_LITERARY_TRADITION_DESCRIPTION",            "每回合+2 [ICON_GREATWRITER] 大作家点数。相邻加成不少于3的剧院广场，其专家产出的 [ICON_GREATWRITER] 大作家点数额外+2。"),
    ("zh_Hans_CN",  "LOC_POLICY_TRANSLATION_DESCRIPTION",                   "学院，剧院广场的相邻加成也会产生对应的 [ICON_TOURISM] 旅游业绩。你的城市若拥有学院或剧院广场，则为通往本城的外国商路提供+1 [ICON_SCIENCE] 科技值或+1 [ICON_CULTURE] 文化值。"),
    ("zh_Hans_CN",  "LOC_POLICY_ARMY_FARM_DESCRIPTION",                     "+100%军营相邻加成。"),
    ("zh_Hans_CN",  "LOC_POLICY_EQUESTRIAN_ORDERS_DESCRIPTION",             "改良的 [ICON_RESOURCE_HORSES] 马与 [ICON_RESOURCE_IRON] 铁每回合额外产出1点资源，若城市采用资源税则翻倍。"),
    ("zh_Hans_CN",  "LOC_POLICY_COASTAL_SURVEY_DESCRIPTION",                "海军单位移动后，会获得5格内村庄，野蛮人营地，以及市中心的位置信息。"),
    ("zh_Hans_CN",  "LOC_POLICY_LIMITANEI_DESCRIPTION",                     "战斗单位为三环内的城市+2忠诚度。"),

    ("zh_Hans_CN",  "LOC_POLICY_CHARISMATIC_LEADER_NAME",           "使节"),
    ("zh_Hans_CN",  "LOC_POLICY_COASTAL_SURVEY_NAME",               "沿海调查"),
    ("zh_Hans_CN",  "LOC_POLICY_TRIBUTE_NAME",                      "朝贡"),
    ("zh_Hans_CN",  "LOC_POLICY_HEDONISM_NAME",                     "享乐主义"),
    ("zh_Hans_CN",  "LOC_POLICY_TRANSLATION_NAME",                  "翻译"),
    ("zh_Hans_CN",  "LOC_POLICY_ARMY_FARM_NAME",                    "军屯"),
    ("zh_Hans_CN",  "LOC_POLICY_EQUESTRIAN_ORDERS_NAME",            "战略储备"),
    ("zh_Hans_CN",  "LOC_POLICY_CAPITAL_NAME",                      "都城"),
    ("zh_Hans_CN",  "LOC_POLICY_COOPERATIVE_COMBAT_NAME",           "协同作战");
